name: package_of_the_day
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # For glowing effect around an avatar
  avatar_glow: ^2.0.2
  # For accessing all google fonts
  google_fonts: ^2.1.0
  # For fancy pull to refresh
  liquid_pull_to_refresh: ^3.0.0
  # For percentage indicator
  percent_indicator: ^3.4.0
  # For Cube Swipe
  flutter_carousel_slider: ^1.0.8
  # For cute & fun dot indicator
  smooth_page_indicator: ^1.0.0+2
  # For awesome icons
  font_awesome_flutter: ^9.2.0
  # For pre-built Animations
  animations: ^2.0.2
  # For Neon signs
  neon: ^0.1.0
  # For Aurora gradient
  aurora: ^1.0.0
  # For banner swiping effects
  flutter_swiper_null_safety: ^1.0.2
  # For displaying blur image while loading
  flutter_blurhash: ^0.6.0
  # For  rendering SVG image
  flutter_svg: ^1.0.0
  # For various custom shapes
  flutter_custom_clippers: ^2.0.0
  # For Text-to-speech in flutter
  flutter_tts: ^3.3.3
  # For Code highlight
  flutter_highlight: ^0.7.0
  # For Drawing charts
  syncfusion_flutter_charts: ^19.4.40
  # For displaying alert pop-up
  rflutter_alert: ^2.0.4
  # For setting ui for both android & iOS
  flutter_settings_ui: ^2.0.1

dev_dependencies:
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/banner/
    - assets/svg/
    - assets/images/rflutter_alert/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
